[2020-04-26 13:22:21,892:data_loader.py:88][DEBUG] >> Folder name: saves for saves already exists.
[2020-04-26 13:22:21,895:data_loader.py:89][DEBUG] >> Folder name: results for results already exists.
[2020-04-26 13:22:21,897:helpers.py:12][DEBUG] >> Trying to restore checkpoint from:C:\Users\iplitharas\PycharmProjects\myPython\Decision_trees\saves\dataset
[2020-04-26 13:22:21,925:logger.py:42][INFO] >> Calling _get_station_codes
[2020-04-26 13:22:22,002:data_loader.py:170][INFO] >> Departure location code is:70086
[2020-04-26 13:22:22,002:data_loader.py:171][INFO] >> Arrival location code is:70068
[2020-04-26 13:22:22,006:logger.py:47][INFO] >> Called _get_station_codes for 0.08s
[2020-04-26 13:22:22,169:helpers.py:12][DEBUG] >> Trying to restore checkpoint from:C:\Users\iplitharas\PycharmProjects\myPython\Decision_trees\saves\dataset
[2020-04-26 13:22:22,190:helpers.py:12][DEBUG] >> Trying to restore checkpoint from:C:\Users\iplitharas\PycharmProjects\myPython\Decision_trees\saves\relative_arrival_times
[2020-04-26 13:22:22,231:helpers.py:12][DEBUG] >> Trying to restore checkpoint from:C:\Users\iplitharas\PycharmProjects\myPython\Decision_trees\saves\relative_arrival_times
[2020-04-26 13:22:22,247:helpers.py:12][DEBUG] >> Trying to restore checkpoint from:C:\Users\iplitharas\PycharmProjects\myPython\Decision_trees\saves\arrival_times
[2020-04-26 13:22:22,260:helpers.py:12][DEBUG] >> Trying to restore checkpoint from:C:\Users\iplitharas\PycharmProjects\myPython\Decision_trees\saves\relative_arrival_times
[2020-04-26 13:22:22,268:helpers.py:12][DEBUG] >> Trying to restore checkpoint from:C:\Users\iplitharas\PycharmProjects\myPython\Decision_trees\saves\arrival_times
[2020-04-26 13:22:50,894:helpers.py:12][DEBUG] >> Trying to restore checkpoint from:C:\Users\iplitharas\PycharmProjects\myPython\Decision_trees\saves\relative_arrival_times
[2020-04-26 13:22:50,899:helpers.py:12][DEBUG] >> Trying to restore checkpoint from:C:\Users\iplitharas\PycharmProjects\myPython\Decision_trees\saves\arrival_times
[2020-04-26 13:23:23,835:helpers.py:12][DEBUG] >> Trying to restore checkpoint from:C:\Users\iplitharas\PycharmProjects\myPython\Decision_trees\saves\relative_arrival_times
[2020-04-26 13:23:23,846:helpers.py:12][DEBUG] >> Trying to restore checkpoint from:C:\Users\iplitharas\PycharmProjects\myPython\Decision_trees\saves\arrival_times
[2020-04-26 13:23:23,872:helpers.py:12][DEBUG] >> Trying to restore checkpoint from:C:\Users\iplitharas\PycharmProjects\myPython\Decision_trees\saves\training
[2020-04-26 13:23:23,879:helpers.py:12][DEBUG] >> Trying to restore checkpoint from:C:\Users\iplitharas\PycharmProjects\myPython\Decision_trees\saves\testing
[2020-04-26 13:23:23,891:helpers.py:12][DEBUG] >> Trying to restore checkpoint from:C:\Users\iplitharas\PycharmProjects\myPython\Decision_trees\saves\relative_arrival_times
[2020-04-26 13:24:04,197:helpers.py:12][DEBUG] >> Trying to restore checkpoint from:C:\Users\iplitharas\PycharmProjects\myPython\Decision_trees\saves\training
[2020-04-26 13:24:04,206:helpers.py:12][DEBUG] >> Trying to restore checkpoint from:C:\Users\iplitharas\PycharmProjects\myPython\Decision_trees\saves\testing
[2020-04-26 13:24:04,214:logger.py:42][INFO] >> Calling create_features
[2020-04-26 13:24:04,235:logger.py:47][INFO] >> Called create_features for 0.02s
[2020-04-26 13:24:45,937:helpers.py:12][DEBUG] >> Trying to restore checkpoint from:C:\Users\iplitharas\PycharmProjects\myPython\Decision_trees\saves\training
[2020-04-26 13:24:45,952:helpers.py:12][DEBUG] >> Trying to restore checkpoint from:C:\Users\iplitharas\PycharmProjects\myPython\Decision_trees\saves\testing
[2020-04-26 13:24:45,958:logger.py:42][INFO] >> Calling create_features
[2020-04-26 13:24:45,986:logger.py:47][INFO] >> Called create_features for 0.02s
